apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tekton-triggers-access
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggers", "triggerbindings", "triggertemplates", "clustertriggerbindings", "clusterinterceptors", "interceptors"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaniko-triggers-binding
subjects:
  - kind: ServiceAccount
    name: kaniko
    namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tekton-triggers-access
  apiGroup: rbac.authorization.k8s.io
