apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: "$(body.head_commit.id)"
    - name: gitrepositoryurl
      value: "$(body.repository.url)"
    - name: IMAGE
      value: "docker.io/kevin593/demo-devops-app:latest"
