apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-node-app
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      description: "Docker image URL incluyendo repo y tag"
      type: string
  workspaces:
    - name: source
      description: "Código fuente de la app"
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=/workspace/source/Dockerfile"
        - "--context=/workspace/source"
        - "--destination=$(params.IMAGE)"
      volumeMounts:
        - name: kaniko-secret
          mountPath: /kaniko/.docker
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-secret
