apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "kevin593",
          "password": "Stalin312.",
          "auth": "$(echo -n kevin593:Stalin312. | base64)"
        }
      }
    }
