apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push-trigger
      binding:
        name: github-push-binding
      template:
        name: build-push-template
