apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-source-pvc
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi
