apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://storage.googleapis.com/tekton-releases/pipeline
    targetRevision: latest
    path: release.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
