apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
---
# Tekton Pipelines v0.60.0 (usa registry.k8s.io)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipelines-controller
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-pipelines-controller
  template:
    metadata:
      labels:
        app: tekton-pipelines-controller
    spec:
      containers:
        - name: controller
          image: registry.k8s.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.60.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipelines-webhook
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-pipelines-webhook
  template:
    metadata:
      labels:
        app: tekton-pipelines-webhook
    spec:
      containers:
        - name: webhook
          image: registry.k8s.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.60.0
