apiVersion: v1
kind: Namespace
metadata:
  name: tekton-pipelines
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-test
  namespace: tekton-pipelines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tekton-test
  template:
    metadata:
      labels:
        app: tekton-test
    spec:
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9

