# tekton/kaniko-task.yaml
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push-task
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
      description: "Docker image to push"
  workspaces:
    - name: source
  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=/workspace/source/Dockerfile"
        - "--context=/workspace/source/"
        - "--destination=$(params.IMAGE)"
        - "--cache=true"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  serviceAccountName: kaniko
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
