apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
    - name: image
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      runAfter:
        - clone-repo
      taskRef:
        name: build-and-push
      params:
        - name: image
          value: $(params.image)
        - name: git-sha
          value: $(tasks.clone-repo.results.commit)
      workspaces:
        - name: source
          workspace: shared-workspace
