apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
    - name: repo-url
      value: https://github.com/kevin593/gitops-eks
    - name: image
      value: docker.io/kevin593/gitops-eks  # sin :latest, Kaniko usará el SHA
    - name: revision
      value: master
  workspaces:
    - name: shared-workspace
      emptyDir: {}
