apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo-devops-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: GIT_REPO
      type: string
    - name: GIT_BRANCH
      type: string
      default: main
  workspaces:
    - name: shared-workspace
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: repo-url
          value: $(params.GIT_REPO)
        - name: branch
          value: $(params.GIT_BRANCH)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-and-push
      runAfter:
        - clone-repo
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace

