apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
    - name: git-revision
    - name: image
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build
      taskRef:
        name: build-and-push
      params:
        - name: git-url
          value: $(params.git-url)
        - name: git-revision
          value: $(params.git-revision)
        - name: image
          value: $(params.image)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace

