apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-
  namespace: tekton-pipelines
spec:
  serviceAccountName: tekton-build-sa

  pipelineRef:
    name: build-and-push-pipeline

  params:
    - name: IMAGE
      value: docker.io/kevin593/app-node:latest

  workspaces:
    - name: shared-workspace
      emptyDir: {}


