apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string

  workspaces:
    - name: shared-workspace

  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone-apps-only
      params:
        - name: repo-url
          value: $(params.repo-url)
      workspaces:
        - name: shared-workspace

    - name: debug-after-clone
      runAfter:
        - clone-repo
      taskSpec:
        steps:
          - name: debug-workspace
            image: alpine
            script: |
              echo "Contenido del workspace DESPUÉS de clone:"
              ls -R $(workspaces.shared-workspace.path)
        workspaces:
          - name: shared-workspace

    - name: build-and-push
      runAfter:
        - debug-after-clone
      taskRef:
        name: build-and-push
      params:
        - name: image
          value: $(params.image)
      workspaces:
        - name: shared-workspace

