apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-build-and-push-node-app
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      description: "Docker image URL"
      type: string
  workspaces:
    - name: source
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push-node-app
      params:
        - name: IMAGE
          value: "$(params.IMAGE)"
      workspaces:
        - name: source
          workspace: source
