apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: build-and-push-run
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-and-push-pipeline
  params:
    - name: repo-url
      value: https://github.com/Kevin593/gitops-eks
    - name: image
      value: docker.io/kevin593/gitops-eks
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: source-pvc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
