apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
    - name: revision
      type: string
      default: master

  workspaces:
    - name: shared-workspace
    - name: k8s

  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: image
          value: $(params.image)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace

    - name: deploy-to-k8s
      runAfter:
        - build-and-push
      taskRef:
        name: deploy-to-k8s
      params:
        - name: image
          value: $(params.image)
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
        - name: k8s
          workspace: k8s
