apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
      description: "Repositorio Git de la aplicación"

    - name: image
      type: string
      description: "Repositorio base de la imagen (sin tag)"

    - name: image-tag
      type: string
      description: "Tag único de la imagen"

    - name: revision
      type: string
      default: master
      description: "Branch o commit a construir"

  workspaces:
    - name: shared-workspace

  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: image
          value: $(params.image):$(params.image-tag)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared-workspace

