# tekton/pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipeline-run-node-app
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: pipeline-build-and-push-node-app
  params:
    - name: IMAGE
      value: "kevin593/demo-devops-app:1.0.0"
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: pvc-source
