apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: build-and-push-run-
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-and-push-pipeline

  params:
    - name: repo-url
      value: https://github.com/Kevin593/gitops-eks
    - name: image
      value: docker.io/kevin593/gitops-eks:latest

  workspaces:
    - name: shared-workspace
      emptyDir: {}

  serviceAccountName: tekton-build-sa









