apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-push-pipeline
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
    - name: revision
      type: string
      default: master

  workspaces:
    - name: shared-workspace

  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: repo-url
          value: $(params.repo-url)
        - name: image
          value: $(params.image)
        - name: revision
          value: $(params.revision)
      workspaces:
        - name: shared-workspace
