# tekton/pvc-source.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-source
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

