# tekton/sa-kaniko.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko
  namespace: tekton-pipelines
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-role
  namespace: tekton-pipelines
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "secrets"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-binding
  namespace: tekton-pipelines
subjects:
  - kind: ServiceAccount
    name: kaniko
    namespace: tekton-pipelines
roleRef:
  kind: Role
  name: kaniko-role
  apiGroup: rbac.authorization.k8s.io
