apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: main
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone -b $(params.revision) $(params.repo-url) $(workspaces.output.path)

