apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: master
    - name: image
      type: string

  workspaces:
    - name: shared-workspace

  steps:
    - name: clone
      image: bitnami/git:2.43.0
      workingDir: $(workspaces.shared-workspace.path)
      script: |
        git clone --single-branch --branch $(params.git-revision) $(params.git-url) .

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.22.0
      workingDir: $(workspaces.shared-workspace.path)
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker/
      args:
        - "--dockerfile=Dockerfile"
        - "--context=."
        - "--destination=$(params.image)"
