apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
  workspaces:
    - name: output
  steps:
    - name: clone-apps-only
      image: alpine/git
      script: |
        #!/bin/sh
        set -e

        echo "Clonando solo la carpeta apps/"

        cd /workspace/output
        git init
        git remote add origin $(params.repo-url)
        git config core.sparseCheckout true

        mkdir -p .git/info
        echo "apps/" > .git/info/sparse-checkout

        git pull origin master

        echo "Contenido final:"
        ls -R .






