apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: URL del repositorio a clonar
  workspaces:
    - name: output
      description: Workspace donde se clonará el repo
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.url) /workspace/output
    - name: show-clone
      image: alpine
      script: |
        #!/bin/sh
        echo "Contenido del workspace después del clone:"
        ls -R /workspace/output



