apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  params:
    - name: url
      type: string
      description: URL del repositorio a clonar
  workspaces:
    - name: output
      description: Workspace donde se clonará el repo
  steps:
    - name: step-clone
      image: alpine/git
      script: |
        #!/bin/sh
        echo "Clonando repositorio..."
        # Clonamos directamente en /workspace/output/gitops-eks para tener path fijo
        git clone $(params.url) /workspace/output/gitops-eks
    - name: step-show-clone
      image: alpine
      script: |
        #!/bin/sh
        echo "Contenido del workspace después del clone:"
        ls -R /workspace/output




