apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: image
      type: string
  workspaces:
    - name: shared-workspace
  steps:
    - name: debug-workspace
      image: alpine
      script: |
        echo "Contenido del workspace ANTES de Kaniko:"
        ls -R $(workspaces.shared-workspace.path)

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      args:
        - --context=$(workspaces.shared-workspace.path)/apps
        - --dockerfile=$(workspaces.shared-workspace.path)/apps/Dockerfile
        - --destination=$(params.image)
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret












