apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-to-k8s
  namespace: tekton-pipelines
spec:
  params:
    - name: image
      type: string
  workspaces:
    - name: shared-workspace
    - name: k8s
  steps:
    - name: copy-manifests
      image: busybox
      script: |
        #!/bin/sh
        set -e
        # Crear carpeta editable en shared-workspace
        mkdir -p $(workspaces.shared-workspace.path)/k8s
        # Copiar todos los manifests desde el workspace read-only
        cp -r $(workspaces.k8s.path)/* $(workspaces.shared-workspace.path)/k8s
        echo "Manifests copiados a shared-workspace:"
        ls -R $(workspaces.shared-workspace.path)/k8s

    - name: kubectl-apply
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e
        # Cambiar la imagen en el deployment usando la copia editable
        sed -i "s|image: .*|image: $(params.image)|" $(workspaces.shared-workspace.path)/k8s/deployment.yaml
        # Aplicar los manifests al cluster
        kubectl apply -f $(workspaces.shared-workspace.path)/k8s
        echo "Manifests aplicados correctamente"




