apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
    - name: revision
      type: string
      default: master

  workspaces:
    - name: shared-workspace

  results:
    - name: git-sha
      description: "SHA corto del commit actual"

  steps:
    - name: clone-repo
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        echo "Clonando repo..."
        cd $(workspaces.shared-workspace.path)
        git clone --branch $(params.revision) --single-branch $(params.repo-url) temp-repo
        mkdir -p apps
        cp -r temp-repo/apps/* apps/
        # Obtener SHA corto del commit
        SHA=$(git --git-dir=temp-repo/.git rev-parse --short HEAD)
        echo "Commit SHA: $SHA"
        # Guardar SHA en el result
        echo $SHA > $(results.git-sha.path)
        rm -rf temp-repo

    - name: debug-docker-secret
      image: busybox
      script: |
        #!/bin/sh
        echo "Revisando /kaniko/.docker"
        ls -l /kaniko/.docker
        cat /kaniko/.docker/config.json || echo "No se puede leer config.json"

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      args:
        - --context=$(workspaces.shared-workspace.path)/apps
        - --dockerfile=$(workspaces.shared-workspace.path)/apps/Dockerfile
        - --destination=$(params.image):$(results.git-sha)
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/config.json
          subPath: .dockerconfigjson

  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
