apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
      type: string
    - name: git-revision
      type: string
      default: master
    - name: image
      type: string

  workspaces:
    - name: shared-workspace

steps:
  - name: clone
    image: ghcr.io/tektoncd/catalog/git-clone:latest
    workingDir: /workspace/shared-workspace
    script: |
      git clone --single-branch --branch $(params.git-revision) $(params.git-url) .

    
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      workingDir: $(workspaces.shared-workspace.path)/apps
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker/
      args:
        - "--dockerfile=Dockerfile"
        - "--context=."
        - "--destination=$(params.image)"

