apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone-apps-only
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: master
  steps:
    - name: clone-apps-only
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e

        echo "Clonando repo completo dentro del workspace"

        cd $(workspaces.shared-workspace.path)

        git clone --branch $(params.revision) --single-branch $(params.repo-url) temp-repo
        mkdir -p apps
        cp -r temp-repo/apps/* apps/
        rm -rf temp-repo

        echo "Contenido final:"
        ls -R $(workspaces.shared-workspace.path)






