apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: image
    - name: git-url
    - name: git-revision
  workspaces:
    - name: shared-workspace
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone -b $(params.git-revision) $(params.git-url) /workspace/shared-workspace

    - name: build-push
      image: gcr.io/kaniko-project/executor:latest
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker
      args:
        - --dockerfile=/workspace/shared-workspace/apps/Dockerfile
        - --context=/workspace/shared-workspace/apps
        - --destination=$(params.image)
