apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
    - name: revision
      type: string
      default: master

  workspaces:
    - name: shared-workspace

  results:
    - name: image-tag
      description: "Tag generado dinámicamente"

  steps:
    - name: clone-repo
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.shared-workspace.path)
        git clone --branch $(params.revision) --single-branch $(params.repo-url) temp-repo
        mkdir -p apps
        cp -r temp-repo/apps/* apps/
        rm -rf temp-repo

    - name: set-image-tag
      image: busybox
      script: |
        #!/bin/sh
        TAG=$(date +%Y%m%d-%H%M%S)
        echo -n "$TAG" > $(results.image-tag.path)
        echo "Tag generado: $TAG"

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      command:
        - /busybox/sh
      args:
        - -c
        - |
          TAG=$(cat /tekton/results/image-tag)
          echo "Pusheando imagen: $(params.image):$TAG"
          /kaniko/executor \
            --context=$(workspaces.shared-workspace.path)/apps \
            --dockerfile=$(workspaces.shared-workspace.path)/apps/Dockerfile \
            --destination=$(params.image):$TAG
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
