apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      description: "Imagen completa con tag"
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /kaniko/executor
      args:
        - "--context=/workspace/source"
        - "--dockerfile=/workspace/source/Dockerfile"
        - "--destination=$(params.IMAGE)"
      env:
        - name: DOCKER_CONFIG
          value: /tekton/home/.docker/
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
  volumeMounts:
    - name: docker-config
      mountPath: /tekton/home/.docker
