apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
  results:
    - name: sha
      description: "SHA corto del último commit"

  steps:
    # 1️⃣ Clonar el repositorio y copiar solo apps
    - name: clone-repo
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        echo "Clonando repo..."
        cd /workspace/shared-workspace
        git clone --branch master --single-branch $(params.repo-url) temp-repo

        # Obtener SHA corto
        SHA=$(git --git-dir=temp-repo/.git rev-parse --short HEAD)
        echo "SHA encontrado: $SHA"
        echo -n $SHA > /tekton/results/sha.result

        # Copiar solo apps
        mkdir -p apps
        cp -r temp-repo/apps/* apps/
        rm -rf temp-repo

        echo "Contenido final del workspace:"
        ls -R /workspace/shared-workspace

    # 2️⃣ Construir y pushear la imagen con Kaniko usando SHA como tag
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      command:
        - /kaniko/executor
      args:
        - --context=/workspace/shared-workspace/apps
        - --dockerfile=/workspace/shared-workspace/apps/Dockerfile
        - --destination=$(params.image):$(results.sha.result)
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/config.json
          subPath: .dockerconfigjson

  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
