apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
    - name: revision
      type: string
      default: master

  workspaces:
    - name: shared-workspace

  steps:
    - name: clone-repo
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        echo "Clonando repo..."
        cd $(workspaces.shared-workspace.path)

        git clone --branch $(params.revision) --single-branch $(params.repo-url) temp-repo

        cd temp-repo
        git rev-parse --short HEAD > ../commit-sha.txt
        echo "Commit SHA: $(cat ../commit-sha.txt)"
        cd ..

        mkdir -p apps
        cp -r temp-repo/apps/* apps/
        rm -rf temp-repo

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.23.2
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
        - name: COMMIT_SHA
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['tekton.dev/taskrun']
      args:
        - --context=$(workspaces.shared-workspace.path)/apps
        - --dockerfile=$(workspaces.shared-workspace.path)/apps/Dockerfile
        - --destination=$(params.image)-$(cat $(workspaces.shared-workspace.path)/commit-sha.txt)
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker/config.json
          subPath: .dockerconfigjson

  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret
