apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: CONTEXT
      type: string
      default: apps
    - name: DOCKERFILE
      type: string
      default: apps/Dockerfile

  workspaces:
    - name: source

  steps:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=$(params.DOCKERFILE)"
        - "--context=$(workspaces.source.path)/$(params.CONTEXT)"
        - "--destination=$(params.IMAGE)"
        - "--skip-tls-verify"


