apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone-apps-only
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: master
  steps:
    - name: clone-apps-only
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e

        echo "Clonando solo la carpeta apps dentro del workspace"

        cd $(workspaces.shared-workspace.path)

        git init
        git remote add origin $(params.repo-url)
        git fetch origin $(params.revision)
        git checkout FETCH_HEAD

        # eliminar todo excepto apps
        find . -mindepth 1 -maxdepth 1 ! -name apps ! -name .git -exec rm -rf {} +

        echo "Contenido final:"
        ls -R






