apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: image
      type: string
    - name: revision
      type: string
      default: master

  workspaces:
    - name: shared-workspace

  steps:
    - name: clone-repo
      image: alpine/git
      script: |
        #!/bin/sh
        git clone --branch $(params.revision) $(params.repo-url) /workspace/shared-workspace

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      script: |
        #!/busybox/sh
        TAG=$(date +%Y%m%d%H%M%S)  # Genera timestamp como tag
        echo "Usando tag: $TAG"
        /kaniko/executor \
          --context=/workspace/shared-workspace \
          --dockerfile=/workspace/shared-workspace/Dockerfile \
          --destination=$(params.image):$TAG \
          --skip-tls-verify
