apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: "URL del repositorio a clonar"
    - name: revision
      type: string
      description: "Branch o tag a clonar"
      default: "main"
  workspaces:
    - name: output
      description: "Workspace donde se clonará el repositorio"
  steps:
    - name: clone
      image: alpine/git
      script: |
        echo "Clonando el repositorio..."
        git clone $(params.url) .
        git checkout $(params.revision)
    
    - name: show-clone
      image: alpine
      script: |
        echo "Contenido del workspace después del clone:"
        ls -R /workspace/output



