apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/TU_USUARIO/gitops-eks.git
    targetRevision: main
    path: tekton

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
