apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-push-template
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      default: "master"
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-push-run-
      spec:
        pipelineRef:
          name: build-and-push-pipeline
        params:
          - name: IMAGE
            value: kevin593/mi-app:$(params.gitrevision)
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: git-source-pvc

