apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  serviceType: NodePort   # 👈 CLAVE (esto cambia todo)
  serviceAccountName: tekton-triggers-sa

  triggers:
    - name: pr-merged-trigger

      interceptors:
        - ref:
            name: github
          params:
            - name: eventTypes
              value: ["pull_request"]

        - ref:
            name: cel
          params:
            - name: filter
              value: >
                body.action == "closed" &&
                body.pull_request.merged == true &&
                body.pull_request.base.ref == "master"

      bindings:
        - ref: github-pr-merged-binding

      template:
        ref: build-and-push-template
