apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: build-and-push-template
  namespace: tekton-pipelines
spec:
  params:
    - name: git-url
    - name: git-revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: build-and-push-run-
      spec:
        pipelineRef:
          name: build-and-push-pipeline
        params:
          - name: repo-url
            value: $(tt.params.git-url)
          - name: revision
            value: $(tt.params.git-revision)
          - name: image
            value: docker.io/kevin593/gitops-eks
        workspaces:
          - name: shared-workspace
            emptyDir: {}
