apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-eks-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=docker.io/kevin593/gitops-eks
    argocd-image-updater.argoproj.io/app.update-strategy: digest
spec:
  project: default

  source:
    repoURL: https://github.com/Kevin593/gitops-eks
    targetRevision: master
    path: k8s
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
