apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-ci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kevin593/gitops-eks
    targetRevision: master
    path: tekton-ci
  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
