apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Kevin593/gitops-eks
    targetRevision: master
    path: tekton

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  managedNamespaceMetadata:
    labels:
      pod-security.kubernetes.io/enforce: baseline
      pod-security.kubernetes.io/audit: baseline
      pod-security.kubernetes.io/warn: baseline







