apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-ci
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: GIT_URL
      type: string
    - name: GIT_REVISION
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: GIT_URL
          value: $(params.GIT_URL)
        - name: GIT_REVISION
          value: $(params.GIT_REVISION)
      workspaces:
        - name: source
          workspace: shared-workspace



