apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-ci
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build-and-push
      taskRef:
        name: build-and-push
      workspaces:
        - name: source
          workspace: shared-workspace

