apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-ci
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: shared-workspace
  tasks:
    - name: build-push
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: shared-workspace
