apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
      default: Dockerfile
    - name: CONTEXT
      type: string
      default: .
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.17.0
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      args:
        - "--dockerfile=$(params.DOCKERFILE)"
        - "--context=$(workspaces.source.path)/$(params.CONTEXT)"
        - "--destination=$(params.IMAGE)"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret

