apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipelines
spec:
  params:
    - name: IMAGE
      type: string
    - name: GIT_URL
      type: string
    - name: GIT_REVISION
      type: string
      default: master

  workspaces:
    - name: source

  podTemplate:
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

  steps:
    - name: clone-repo
      image: alpine/git
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
      script: |
        git clone -b $(params.GIT_REVISION) $(params.GIT_URL) $(workspaces.source.path)

    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.17.0
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      args:
        - "--dockerfile=$(workspaces.source.path)/Dockerfile"
        - "--context=$(workspaces.source.path)"
        - "--destination=$(params.IMAGE)"
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker

  volumes:
    - name: docker-config
      secret:
        secretName: dockerhub-secret

