apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-template
  namespace: tekton-pipelines
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-
      spec:
        serviceAccountName: kaniko-sa
        pipelineRef:
          name: build-push
        params:
          - name: IMAGE
            value: kevin593/mi-app:latest
