apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
